version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: stepp2p-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: stepp2p
      POSTGRES_PASSWORD: stepp2p
      POSTGRES_DB: stepp2p
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
